### ISSUE TITLE
Error code 12: unknown service lnrpc.Lightning

### ISSUE THREAD

**Issue by Cotix** [mably/lncli-web#102]
I've set it up as described in the README with LND and btcd. However on every request the frontend makes I get the following HTTP error:
```
{
   "code":12,
   "metadata": {
      "_internal_repr":{}
    },
   "error":"unknown service lnrpc.Lightning"
}
```

**Comment by Cotix** [comment]
Starting LND with --no-macaroons  --noencryptwallet fixed the issue for me. I suppose something with the macaroons is going wrong. Not sure if its on my end or if lncli-web is a bit buggy here.

**Comment by mably** [comment]
Yep, it hasn't been fully implemented and tested yet.

**Comment by mably** [comment]
lnd is now fully compatible with encrypted wallet and macaroons.

**Comment by beetee2** [comment]
I still get this error. Using encrypted wallet + macaroons.

**Comment by peschu123** [comment]
I get this error too...

**Comment by ellismarte** [comment]
same
