### ISSUE TITLE
Wallet encryption & macaroons

### ISSUE THREAD

**Issue by skddc** [mably/lncli-web#109]
The requirements section states:

> lnd should be started with wallet encryption and macaroons disabled.

However, wallet encryption is an essential part of node security and macaroons are also not a bad idea for bearer tokens. May I ask what the plans for this in combination with lncli-web are?

**Comment by skddc** [comment]
Hmm, I just found https://github.com/mably/lncli-web/commit/04cf038f9cfa8c1e2ae7bc95d28afff66a40b0b1 so maybe it's just not documented yet.

**Comment by mably** [comment]
Some code has been added for macaroons handling: 04cf038f9cfa8c1e2ae7bc95d28afff66a40b0b1

But I didn't have time to test it.  Feel free to contribute on that part.

I guess it should be possible to handle encrypted wallets too but haven't been able to work on it yet.

Any contributions are welcome.

**Comment by skddc** [comment]
Cool, thanks.

**Comment by mably** [comment]
Pushed a fix that allows lncliweb to work with macaroons.

Verified at the same time that lncliweb works perfectly fine with an encrypted wallet.

**Comment by skddc** [comment]
Great!
