### ISSUE TITLE
SSL Handshake Failure

### ISSUE THREAD

**Issue by robertjuric** [mably/lncli-web#113]
I just installed lncli-web and followed the instructions to regenerate the certificates in README.md. When I go to start `node server` I get the following error:

`E0120 18:49:12.754048113    6096 ssl_transport_security.cc:976] Handshake failed with fatal error SSL_ERROR_SSL: error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure.`

lncli-web will start and load the page, but no data from lnd is able to be read.

**Comment by mably** [comment]
Make sure that the `lnd.cert` file in your web app root directory is exactly the same as the one used by lnd.

**Comment by robertjuric** [comment]
I originally overlooked the `.lnd` directory, and was working in the sourcecode directory. However I removed all the files and repeated the process generating the `tls.cert` in the actual `.lnd` directory with the same results.

Just to verify the web app root directory is the directory I have the source code stored right? Or is it considered somewhere else?

**Comment by robertjuric** [comment]
Pay attention to the instructions, the `openssl` commands to generate the new cert needs to be done from `.lnd` directory.

**Comment by mably** [comment]
Feel free to suggest any improvement that could be made to the documentation.

**Comment by ianrussel** [comment]
I got same Isssue, lnd.cert file in web app root directory. Inspected both files is exactly the same as the one used by lnd ( called tls.cert in .lnd directory).
