### ISSUE TITLE
Cant run on Windows Using Vagrant

### ISSUE THREAD

**Issue by ianrussel** [mably/lncli-web#115]
Lnd and Btc is running and port 8280 for service.js runs. But accessing host using private IP e.g 192.168.10.10:8280 does not(refused to connect). Any ideas for this?

**Comment by mably** [comment]
Not using Vagrant. Is the web app reachable from the vagrant vm using a `curl` command for example?

**Comment by ianrussel** [comment]
@mably Yes web app reachable from the vagrant vm using a curl command. Actually, It's my fault, I should have start the nodejs server with the private ip option


            node server --serverhost 192.168.10.10

Can I suggest something? Maybe we can add .env in the root folder then in config/default.js we can change to

              module.exports = {
	          serverHost: process.env.ENV_HOST,   <==
	            ......
	             lndProto: __dirname + "/rpc.proto",
	           ........
               };

running node server should be fine as long ENV_HOST value in .env has correct serverhost value?

**Comment by mably** [comment]
You can definitely do that, you are free to put whatever you want in that `default.js` config file.
