### ISSUE TITLE
detection of mainnet / testnet - link to the respective block explorer

### ISSUE THREAD

**Issue by goodc0re** [mably/lncli-web#118]
At present, when lncli-web is being used with a mainnet lnd node, the links to the block explorer point to https://testnet.smartbit.com.au. 
Maybe lncli-web could detect if mainnet or testnet is being used and point to the correct block explorer.

**Comment by mably** [comment]
https://i.imgur.com/9S0D7n8.png

**Comment by mably** [comment]
![image](https://user-images.githubusercontent.com/385653/35765783-64da356e-08cb-11e8-8e54-819837054177.png)
