### ISSUE TITLE
app crash when selecting Tools --> Network Graph

### ISSUE THREAD

**Issue by peschu123** [mably/lncli-web#127]
When I select Network Graph from tools menu: 
first it writes a lot lines like the first line in the code box and than crashes.

```sh
"0229edafa4127e98e5b023a1920524f702ac183834b17fa69a04714c8c4401f181" -- "03310b9622bcf69661d93eb05e4fe951620cdd4e0af06f008c901936ab68f71518" [ label = " 5711303199", fontsize = 12.0 ];
}

events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn dot ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by mably** [comment]
Does it work fine when using the `lncli` command-line tool?

**Comment by peschu123** [comment]
Can you pls specify which command you exactly referring to?
I tried  `lncli describegraph` which works fine.

**Comment by mably** [comment]
I think you have a `--render` option or something similar to produce a corresponding SVG file.  Have you tried it?

**Comment by couillardcharles** [comment]
The `dot` tool is needed, available here: https://www.graphviz.org/

You can install the `graphviz` package on ubuntu/debian.

@mably You should check the availability of the `dot` tool before trying to build the network graph :)

**Comment by mably** [comment]
#138 should now display a warning message if the graphviz package is not installed on the server.

**Comment by PotatoBlood** [comment]
I get 
`Error: ENOENT: no such file or directory, stat '/home/pi/lncli-web/data/networkgraph.svg'`
and the dot process taking up 30% cpu and not doing much

graphviz installed.

**Comment by mably** [comment]
It seems that the graph generation process on mainnet can take quite a long time, several minutes at least.

**Comment by PotatoBlood** [comment]
ok, took almost 24h to generate the graph on my raspberry pi 3,
it made a huuuuge file, here's a small part of it lol: https://puu.sh/AoAP7/4377d8e586.jpg

**Comment by mably** [comment]
I guess this feature is getting pretty useless on mainnet now ;)
