### ISSUE TITLE
undefined symbol: SSL_library_init

### ISSUE THREAD

**Issue by enorrmann** [mably/lncli-web#135]
Followed the build instructions under ubuntu 18.04 but when I try to 

node server

app wont start with error
node: symbol lookup error: /home/emilio/lncli-web/node_modules/grpc/src/node/extension_binary/node-v57-linux-x64-glibc/grpc_node.node: undefined symbol: SSL_library_init

**Comment by mably** [comment]
Never tried it with Ubuntu 18.06 only 16.04.  What is your nodejs version ? `node -v`

**Comment by enorrmann** [comment]
NodeJs v8.10.0
OpenSSL 1.1.0g  2 Nov 2017

**Comment by enorrmann** [comment]
updated nodejs to last version 

curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
sudo apt-get install -y nodejs

and now it is running :dancer:

**Comment by mably** [comment]
Great! Thanks for sharing the solution to your problem 👍
