### ISSUE TITLE
no data in the webpage

### ISSUE THREAD

**Issue by Fr4nZ82** [mably/lncli-web#147]
after update lnd to latest commit node server start whit no errors but i can see only static text in the webpage, no data... I already tried to update lncli-web and nodejs, and regenerate lnd.cert

**Comment by mably** [comment]
Just updated my lnd nodes to latest master, lncli-web still working fine 🤔

**Comment by Fr4nZ82** [comment]
any suggestion on how to troubleshot this problem? If i active debug loglevel i see the output of lnd...

**Comment by jhizzle84** [comment]
Are there any rpc errors when you expand some of the elements?
