### ISSUE TITLE
Channel Balance missing balances

### ISSUE THREAD

**Issue by halfik** [mably/lncli-web#154]
Take a look on screenshot: https://ibb.co/jOABE8

I have 3 open channels that are active and 1 that is inactive.
using lnd 0.4.2-beta

**Comment by mably** [comment]
Are you on latest master? Balances are correctly displayed for my nodes.

**Comment by halfik** [comment]
Yep, latest master.

**Comment by drunkenclam** [comment]
Same problem here (master from 2 days ago), but wallet balance missing as well. JSON shows correct amounts:

![image](https://user-images.githubusercontent.com/10271314/42831747-77dc1b32-89ef-11e8-8562-85a315c3dae6.png)

**Comment by mably** [comment]
Check your display units in the Tools > Settings dialog: 

![image](https://user-images.githubusercontent.com/385653/42831878-d39b6b62-89ef-11e8-9f20-5399fc11aef9.png)

**Comment by drunkenclam** [comment]
Working now! Thanks!

**Comment by halfik** [comment]
Didnt help me.
Still have no wallet and channel balaneces summary. Only thing that works is if i restart server.

**Comment by mably** [comment]
Should be fixed now.
