### ISSUE TITLE
empty web page with lnd 0.5beta

### ISSUE THREAD

**Issue by enorrmann** [mably/lncli-web#159]
I updated lnd to the latest commit, and the server is still running, and connecting, but no data is showing

**Comment by 4oo4** [comment]
@enorrmann That happened to me too, I think what fixed it for me was updating me macaroons (admin.macaroon, macaroons.db invoice.macaroon, etc) in the lncli-web folder.

**Comment by enorrmann** [comment]
thx @4oo4 I will try that

**Comment by enorrmann** [comment]
didn't work
even reinstalling from scratch

**Comment by enorrmann** [comment]
copying macaroons from
.lnd/data/chain/bitcoin/testnet/admin.macaroon
did the trick

**Comment by mably** [comment]
Thanks for sharing your solution to your problem 👍
