### ISSUE TITLE
found 152 vulnerabilities (144 low, 4 moderate, 4 high)

### ISSUE THREAD

**Issue by alanrburns** [mably/lncli-web#166]
Hi 
There seems to be many vulnerabilities.
Will this be addressed?

how to replicate:
$ node -v
v8.12.0
$ npm -v
6.4.1
$ git clone https://github.com/mably/lncli-web.git
$ cd lncli-web
$ npm audit
found 152 vulnerabilities (144 low, 4 moderate, 4 high) in 7405 scanned packages
  run `npm audit fix` to fix 142 of them.
  7 vulnerabilities require semver-major dependency updates.
  3 vulnerabilities require manual review. See the full report for details.

After running 'npm audit fix'
found 10 vulnerabilities (6 low, 4 high) in 7603 scanned packages
  7 vulnerabilities require semver-major dependency updates.
  3 vulnerabilities require manual review. See the full report for details.

**Comment by mably** [comment]
Excellent, could you make a PR for this?

**Comment by mably** [comment]
Pushed package files after running a simple `npm audit fix`

**Comment by alanrburns** [comment]
Thanks looks like there are now just 4 low severity vulnerabilities..
