### ISSUE TITLE
NaN  in channel capacity and missing info

### ISSUE THREAD

**Issue by enorrmann** [mably/lncli-web#204]
running master branch
with LND  0.8.2-beta commit=v0.8.2-beta
there is some missing information and NaNs

https://imgur.com/gallery/t4rGluj

**Comment by mably** [comment]
Sadly, for the time being I don't have much time to dedicate to this project anymore.

If anybody wants to have a look at this issue, feel free.

**Comment by enorrmann** [comment]
thx ! I will !
