### ISSUE TITLE
Feature Request:  Read only mode

### ISSUE THREAD

**Issue by DavinciCodes15** [mably/lncli-web#211]
Hi My name is Davinci

I got lncli-web up and running and I am wondering if you have a read-only mode so you viewers have no access to the money or private keys for signing.

They can only see what's going on.

**Comment by mably** [comment]
As far as I remember, a read-only mode is available.  I think you just have to use a specific pair of login/password.  Haven't been working on the project for a while.

**Comment by DavinciCodes15** [comment]
Thanks, I just used a readonly.macroon and that what I needed.
