### ISSUE TITLE
Missing babel-core dev dependency

### ISSUE THREAD

**Issue by jaycuse** [mably/lncli-web#99]
Got an error after running `"./node_modules/.bin/gulp" bundle`

> Error: Cannot find module 'babel-core' 

Didn't see it listed in `package.json` file.

I was able to fix it by manually installing it using:
`npm install babel-core babel-loader --save-dev`

Adding it as an issue, because you may want to add it to the `package.json` file.

**Comment by mandelmonkey** [comment]
would be nice to update the package is a lot of tutorial readers may get stumped here

**Comment by mably** [comment]
Ok, seems related to this: https://github.com/babel/gulp-babel/issues/124

Will add it as a dependency.
